### ISSUE TITLE
Total per interval (day?)

### ISSUE THREAD

**Issue by vanous** [marq24/UUID0xFD6FTracer#10]
Awesome job, thank you! Confirmed to work with new CZ covid warn app ("e-facemask" (eRouška)).
Any chance to add a counter to show how many unique IDs were seen in a day?
cheers

**Comment by marq24** [comment]
Thanks for your positive feedback!

Concerning your feature request - one of the key aspects of the app design was/is not to store any BTLE-Beacon data on the device - another one is to keep the app as simple as possible in order to make it as stable as possible and most energy efficient as possible.

When you want to do some statistics (and there have been already requests for that) then you can use my GPSLoggerII app for that - The app comes with a special BTLE-Beacon CVS Export (of an recorded path) that would allow you to do the stats you would like to do/have in a spreadsheet app.

...thinking...  mmmmmh - on the other hand side you are "just asking" for a second number - displaying the total number of Beacons (and having the possibility to manually reset that total counter - I would not add a autoreset every 24h)... The only challenge will be/is: https://github.com/marq24/UUID0xFD6FTracer/blob/master/LOGGING_de.md#z%C3%A4hlweise

**Comment by marq24** [comment]
In the 0.9.1.9 build you will find an additional Setting to enable the display of the total found Beacons (you can reset the value by restarting the service)

**Comment by vanous** [comment]
Self compiled, got it in there, awesome!
Thank you!

**Comment by Citro12** [comment]
Hallo, mit der neuen Version steht der Zähler von der französischen StopCovid auf 1, obwohl nur ein Sender der deutschen Corona App anwesend ist. StopCovid geht dann aber nach einiger Zeit auf 0 zurück. Ist das richtig so ?

**Comment by marq24** [comment]
upsi - fixed in 0.9.1.10

**Comment by Citro12** [comment]
> upsi - behoben in 0.9.1.10

Funktioniert, Danke

**Comment by marq24** [comment]
wunder der SoftwareEntwicklung - kaum mach't man's richtig... schon funktioniert's
