### ISSUE TITLE
No errormessage/optical clue if  not working because bluetooth is disabled

### ISSUE THREAD

**Issue by k3b** [marq24/UUID0xFD6FTracer#11]
when i start the app while bluetooth is disabled i get no errormessage or ohter optical clue that the app is not working.

I am not shure if the app is working at all on my android-9 device: i tested the app while entering/riding/leaving 3 crowded commuter trains and got no "Aktaive Sender-s".

Is there any way how to check if the app works on my android device while not having an other android device with a running corona app?

**Comment by marq24** [comment]
That's correct - It did not came to my mind yet, that if BT is disabled on the device there is no kind of information or warning... Looks like it was/is so natural for me, that BT is enabled since it's mandatory for all CoronaWarnApps... It did not came to my mind yet, that you want to use the App without running a WarnApp yourself... But what ever is the reason for that - integrating a waring/info (if BT is disabled) would not hurt at all...

For your second point - There could be multiple reasons, why the App did not work for you - one of them could be, that the app is os restricted in background mode (that's why the new 0.9.1.9+ have an additional setting disable this "os-optimization"... Another reason could be, that if BT was disabled when you started the app, that then the scanner would never be activated (even if you have enabled BT later) - that's something I will add/check... 

But in general the "only" way to see/test if the app is working is having a second phone with a WarnApp running - or connect the phone via USB and check the logcat output (which might be already a bit to complicated)

**Comment by marq24** [comment]
please check v0.9.1.11

**Comment by k3b** [comment]
thanks for taking the time for enhancing the app.
One way to test the app might be to detect any bluetooth-signal (without the special signature).

As soon as the app appears i f-droid i will check it.

---

>  that you want to use the App without running a WarnApp yourself.

the warnig app requires some non-opensource playservice extension that is not running on de-googled devicesor or on devices with non-google-account

**Comment by marq24** [comment]
update is available @ F-Droid...

**Comment by k3b** [comment]
i have found out that the app only works on ma android-9 device if 

* bluetooth is enabled
* and Location is enabled

bluetooth detection is now working as expected. Can you also add "Location " detection ?

**Comment by marq24** [comment]
added in 0.9.1.14 - thanks for the note!

**Comment by marq24** [comment]
I'll guess I can clos this one now - right?

**Comment by k3b** [comment]
yesterday i installed version 0.9.1.14

i found these issues:

if gps and bluetooth are disabled before app start the error detection works except that the german display say "please enable bluetooth" (Bitte aktivieren sie Bluetooth) even if bluetooth is enabled and gps is disabled.

a message "please enable bluetooth and gps" would be better.

when i disable blue tooth the error message re-appears as expected.

if i have bluetooth enabled and disable gps than there is no error message.

note: since yesterday my device has android-10

**Comment by marq24** [comment]
with the 0.9.1.15 this is finally done (combined info)
